version: "3.8"
services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www/html
        volumes:
                - ./:/var/www/html
        ports:
            - "8000:8000"
        environment:
            DATABASE_USER: ${DATABASE_USER}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            DATABASE_HOST: ${DATABASE_HOST}
            DATABASE_PORT: ${DATABASE_PORT}
            DATABASE_NAME: ${DATABASE_NAME}
        command: php -S 0.0.0.0:8000 -t public

    mysql:
        image: mariadb:10.8.3
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MARIADB_USER=${DATABASE_USER}
            - MARIADB_ROOT_PASSWORD=${DATABASE_PASSWORD}
            - MARIADB_PASSWORD=${DATABASE_PASSWORD}
            - MARIADB_DATABASE=${DATABASE_NAME}
        ports:
            - "3330:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        ports:
            - "8082:8080"


volumes:
    mysql_data:
